//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eticarett.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banka
    {
        public Banka()
        {
            this.Taksitler = new HashSet<Taksitler>();
        }
    
        public int Id { get; set; }
        public string BankaAdi { get; set; }
        public byte[] Bankalogo { get; set; }
    
        public virtual ICollection<Taksitler> Taksitler { get; set; }
    }
}
