//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eticarett.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entitie : DbContext
    {
        public Entitie()
            : base("name=Entitie")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Banka> Banka { get; set; }
        public DbSet<Kampanya> Kampanya { get; set; }
        public DbSet<Kargo> Kargo { get; set; }
        public DbSet<Katagori> Katagori { get; set; }
        public DbSet<Markalar> Markalar { get; set; }
        public DbSet<OdemeSecenekleri> OdemeSecenekleri { get; set; }
        public DbSet<OzellikDetay> OzellikDetay { get; set; }
        public DbSet<Resimler> Resimler { get; set; }
        public DbSet<Roller> Roller { get; set; }
        public DbSet<Sepet> Sepet { get; set; }
        public DbSet<SiparisDurumu> SiparisDurumu { get; set; }
        public DbSet<Siparisler> Siparisler { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Taksitler> Taksitler { get; set; }
        public DbSet<TaksitTaplosu> TaksitTaplosu { get; set; }
        public DbSet<UrunFiyat> UrunFiyat { get; set; }
        public DbSet<Urunler> Urunler { get; set; }
        public DbSet<UrunOzellikler> UrunOzellikler { get; set; }
        public DbSet<Üye> Üye { get; set; }
    }
}
