//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eticarett.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entitie : DbContext
    {
        public Entitie()
            : base("name=Entitie")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Banka> Banka { get; set; }
        public virtual DbSet<Kampanya> Kampanya { get; set; }
        public virtual DbSet<Kargo> Kargo { get; set; }
        public virtual DbSet<Katagori> Katagori { get; set; }
        public virtual DbSet<Markalar> Markalar { get; set; }
        public virtual DbSet<OdemeSecenekleri> OdemeSecenekleri { get; set; }
        public virtual DbSet<Ozellik> Ozellik { get; set; }
        public virtual DbSet<Resimler> Resimler { get; set; }
        public virtual DbSet<Roller> Roller { get; set; }
        public virtual DbSet<Sepet> Sepet { get; set; }
        public virtual DbSet<SiparisDurumu> SiparisDurumu { get; set; }
        public virtual DbSet<Siparisler> Siparisler { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Taksitler> Taksitler { get; set; }
        public virtual DbSet<TaksitTaplosu> TaksitTaplosu { get; set; }
        public virtual DbSet<UrunDetaylari> UrunDetaylari { get; set; }
        public virtual DbSet<UrunFiyat> UrunFiyat { get; set; }
        public virtual DbSet<Urunler> Urunler { get; set; }
        public virtual DbSet<Üye> Üye { get; set; }
    }
}
