//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eticarett.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OzellikDetay
    {
        public int Id { get; set; }
        public int UrunId { get; set; }
        public int UrunOzellikId { get; set; }
        public string ÖzellikDetay { get; set; }
    
        public virtual Urunler Urunler { get; set; }
        public virtual UrunOzellikler UrunOzellikler { get; set; }
    }
}
