//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eticarett.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparisler
    {
        public int Id { get; set; }
        public int UrunId { get; set; }
        public int DurumId { get; set; }
        public int ÖdemeSecenkleriId { get; set; }
        public int TaksitId { get; set; }
        public System.DateTime SiparisTarihi { get; set; }
        public int KargoId { get; set; }
        public decimal KargoNo { get; set; }
        public System.DateTime OngorulenTeslimTarihi { get; set; }
        public System.DateTime TeslimTarihi { get; set; }
    
        public virtual Kargo Kargo { get; set; }
        public virtual OdemeSecenekleri OdemeSecenekleri { get; set; }
        public virtual SiparisDurumu SiparisDurumu { get; set; }
        public virtual Taksitler Taksitler { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
