//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eticarett.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taksitler
    {
        public Taksitler()
        {
            this.Siparisler = new HashSet<Siparisler>();
        }
    
        public int Id { get; set; }
        public int BankaId { get; set; }
        public int UrunId { get; set; }
        public int TaksitTaploId { get; set; }
    
        public virtual Banka Banka { get; set; }
        public virtual ICollection<Siparisler> Siparisler { get; set; }
        public virtual TaksitTaplosu TaksitTaplosu { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
