//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eticarett.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunOzellikler
    {
        public UrunOzellikler()
        {
            this.OzellikDetay = new HashSet<OzellikDetay>();
        }
    
        public int Id { get; set; }
        public string OzellikAdi { get; set; }
    
        public virtual ICollection<OzellikDetay> OzellikDetay { get; set; }
    }
}
