//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eticarett.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Üye
    {
        public int Id { get; set; }
        public string Isim { get; set; }
        public string Soyisim { get; set; }
        public string Adres { get; set; }
        public string Eposta { get; set; }
        public string Tel { get; set; }
        public string Parola { get; set; }
        public string GuvenlikSorusu { get; set; }
        public string GuvenlikCevabı { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public int RolId { get; set; }
    
        public virtual Roller Roller { get; set; }
    }
}
